# Generated by Django 4.1.4 on 2025-03-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prid', models.IntegerField()),
                ('custid', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('iname', models.CharField(max_length=20)),
                ('imagepath', models.ImageField(null=True, upload_to='images')),
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='usercred',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('Cpassword', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('yourname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('cross_and_main', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('total_price', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userreq',
            fields=[
                ('yourname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.userdetails')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agro.userinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.item')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.PositiveIntegerField(default=1)),
                ('cross_and_main', models.CharField(default='Unknown', max_length=255)),
                ('area', models.CharField(default='Unknown', max_length=255)),
                ('district', models.CharField(default='Unknown', max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.userdetails')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.userdetails'),
        ),
    ]
