# Generated by Django 4.1.4 on 2025-03-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0002_remove_item_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='name',
        ),
        migrations.AddField(
            model_name='addcart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agro.item'),
        ),
    ]
