# Generated by Django 4.1.4 on 2025-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0003_remove_addcart_name_addcart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='product',
        ),
        migrations.AddField(
            model_name='addcart',
            name='name',
            field=models.CharField(default='default_name', max_length=30),
        ),
    ]
