# Generated by Django 4.1.4 on 2025-03-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0004_remove_addcart_product_addcart_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='id',
        ),
        migrations.AlterField(
            model_name='addcart',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='prid',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
