# Generated by Django 4.1.4 on 2025-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0005_remove_addcart_id_alter_addcart_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='prid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
