# Generated by Django 4.1.4 on 2025-03-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0006_alter_addcart_prid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='prid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='imagepath',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
