# Generated by Django 4.1.4 on 2025-03-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0007_alter_addcart_prid_alter_item_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
