# Generated by Django 4.1.4 on 2025-03-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0008_alter_item_iname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='prid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='imagepath',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='iname',
            field=models.CharField(default='Default_Item_Name', max_length=20),
        ),
    ]
