# Generated by Django 4.1.4 on 2025-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0009_alter_addcart_prid_alter_item_imagepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iname',
            field=models.CharField(max_length=20),
        ),
    ]
