# Generated by Django 4.1.4 on 2025-03-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0010_alter_item_iname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagepath',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='iname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
