# Generated by Django 4.1.4 on 2025-03-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0011_alter_item_imagepath_alter_item_iname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagepath',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
