# Generated by Django 4.1.4 on 2025-03-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0019_item_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
    ]
