# Generated by Django 4.1.4 on 2025-03-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0020_remove_item_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.CharField(max_length=10)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_location', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.userinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.item')),
            ],
        ),
    ]
