# Generated by Django 4.1.4 on 2025-03-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0021_ordersummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderSummary',
        ),
    ]
